[2024-12-03T19:12:12.180+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T19:12:12.206+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-12-03T19:12:08.129387+00:00 [queued]>
[2024-12-03T19:12:12.212+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-12-03T19:12:08.129387+00:00 [queued]>
[2024-12-03T19:12:12.213+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-03T19:12:12.225+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-12-03 19:12:08.129387+00:00
[2024-12-03T19:12:12.242+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2816) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T19:12:12.245+0000] {standard_task_runner.py:63} INFO - Started process 2818 to run task
[2024-12-03T19:12:12.245+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-12-03T19:12:08.129387+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp8ytzkxr6']
[2024-12-03T19:12:12.249+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask dbt_run
[2024-12-03T19:12:12.290+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-12-03T19:12:08.129387+00:00 [running]> on host 2adeb2e19af7
[2024-12-03T19:12:12.354+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T19:12:08.129387+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T19:12:08.129387+00:00'
[2024-12-03T19:12:12.357+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T19:12:12.359+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-03T19:12:12.360+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/final_dbt --project-dir /opt/***/final_dbt']
[2024-12-03T19:12:12.373+0000] {subprocess.py:86} INFO - Output:
[2024-12-03T19:12:13.863+0000] {subprocess.py:93} INFO - [0m19:12:13  Running with dbt=1.8.7
[2024-12-03T19:12:14.558+0000] {subprocess.py:93} INFO - [0m19:12:14  Registered adapter: snowflake=1.8.4
[2024-12-03T19:12:14.898+0000] {subprocess.py:93} INFO - [0m19:12:14  Encountered an error:
[2024-12-03T19:12:14.900+0000] {subprocess.py:93} INFO - Compilation Error in snapshot job_listings_snapshot (snapshots/job_listings_snapshot.sql)
[2024-12-03T19:12:14.902+0000] {subprocess.py:93} INFO -   invalid syntax for function call expression
[2024-12-03T19:12:14.904+0000] {subprocess.py:93} INFO -     line 4
[2024-12-03T19:12:14.906+0000] {subprocess.py:93} INFO -       config(
[2024-12-03T19:12:15.627+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-03T19:12:15.630+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T19:12:15.659+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-03T19:12:15.667+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-12-03T19:12:08.129387+00:00, execution_date=20241203T191208, start_date=20241203T191212, end_date=20241203T191215
[2024-12-03T19:12:15.686+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 67 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 2818)
[2024-12-03T19:12:15.731+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-03T19:12:15.780+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T19:12:15.788+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
