[2024-12-03T06:39:03.421+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T06:39:03.445+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: job_listings_etl_v2.extract_api manual__2024-12-03T06:38:59.784996+00:00 [queued]>
[2024-12-03T06:39:03.457+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: job_listings_etl_v2.extract_api manual__2024-12-03T06:38:59.784996+00:00 [queued]>
[2024-12-03T06:39:03.459+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-12-03T06:39:03.468+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_api> on 2024-12-03 06:38:59.784996+00:00
[2024-12-03T06:39:03.487+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=317) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T06:39:03.492+0000] {standard_task_runner.py:63} INFO - Started process 321 to run task
[2024-12-03T06:39:03.498+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'job_listings_etl_v2', 'extract_api', 'manual__2024-12-03T06:38:59.784996+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/ETL_FINAL_PROJECT (1).py', '--cfg-path', '/tmp/tmp7vawry11']
[2024-12-03T06:39:03.504+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask extract_api
[2024-12-03T06:39:03.676+0000] {task_command.py:426} INFO - Running <TaskInstance: job_listings_etl_v2.extract_api manual__2024-12-03T06:38:59.784996+00:00 [running]> on host 2adeb2e19af7
[2024-12-03T06:39:03.973+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='job_listings_etl_v2' AIRFLOW_CTX_TASK_ID='extract_api' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T06:38:59.784996+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T06:38:59.784996+00:00'
[2024-12-03T06:39:03.983+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T06:39:05.017+0000] {ETL_FINAL_PROJECT (1).py:51} ERROR - API request failed: 401 Client Error: Unauthorized for url: https://api.adzuna.com/v1/api/jobs/us/search/1?app_id=92134eab&app_key=%2A%2A%2A%2A%2A%2A%2A%2A&results_per_page=100&what=software+engineer&content-type=application%2Fjson
[2024-12-03T06:39:05.032+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T06:39:05.081+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/ETL_FINAL_PROJECT (1).py", line 48, in extract_api
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.adzuna.com/v1/api/jobs/us/search/1?app_id=92134eab&app_key=%2A%2A%2A%2A%2A%2A%2A%2A&results_per_page=100&what=software+engineer&content-type=application%2Fjson

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_FINAL_PROJECT (1).py", line 52, in extract_api
    raise AirflowException(f"Failed to fetch data from Adzuna API: {str(e)}")
airflow.exceptions.AirflowException: Failed to fetch data from Adzuna API: 401 Client Error: Unauthorized for url: https://api.adzuna.com/v1/api/jobs/us/search/1?app_id=92134eab&app_key=%2A%2A%2A%2A%2A%2A%2A%2A&results_per_page=100&what=software+engineer&content-type=application%2Fjson
[2024-12-03T06:39:05.139+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=job_listings_etl_v2, task_id=extract_api, run_id=manual__2024-12-03T06:38:59.784996+00:00, execution_date=20241203T063859, start_date=20241203T063903, end_date=20241203T063905
[2024-12-03T06:39:05.195+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task extract_api (Failed to fetch data from Adzuna API: 401 Client Error: Unauthorized for url: https://api.adzuna.com/v1/api/jobs/us/search/1?app_id=92134eab&app_key=%2A%2A%2A%2A%2A%2A%2A%2A&results_per_page=100&what=software+engineer&content-type=application%2Fjson; 321)
[2024-12-03T06:39:05.267+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-03T06:39:05.314+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T06:39:05.316+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
